import test from 'node:test';import assert from 'node:assert/strict';
import {mkdtempSync,mkdirSync,writeFileSync,symlinkSync}from'node:fs';import{join,dirname}from'node:path';import{tmpdir}from'node:os';import{createHash}from'node:crypto';
import{canonicalRoot,readPackageFile,verifyPackagePins,smokeRequests,validateSmokeOutput}from'./verify-native-package.mjs';
const sha=x=>createHash('sha256').update(x).digest('hex');
// These tiny inert fixtures exercise validation only; they are never executed.
function fixture(){const root=mkdtempSync(join(tmpdir(),'native-package-unit-')),platform=join(root,'platform'),host=join(root,'host'),audit=join(root,'audit');for(const d of [platform,host,audit])mkdirSync(d);
 const put=(dir,path,value)=>{mkdirSync(dirname(join(dir,path)),{recursive:true});writeFileSync(join(dir,path),typeof value==='object'&&!Buffer.isBuffer(value)?JSON.stringify(value):value);};
 const elf=Buffer.from([127,69,76,70,0]),patch='fixture patch',dpkg='fixture dpkg';
 const pkg={name:'@jhckevin/dsh-auto-review-bridge-linux-x64-gnu',version:'0.1.0-rc.2'},hp={name:'@jhckevin/dsh-auto-review-bridge-host',version:pkg.version,optionalDependencies:{[pkg.name]:pkg.version}};
 const manifest={upstreamCommit:'9f97cb79eb15b38d24c552c56fe24e211ff9cf3a',platform:'linux-x64-gnu',minimumGlibc:'2.31',bridge:{path:'bin/codex-approval-protocol-bridge',size:elf.length,sha256:sha(elf)},launcher:{path:'bin/landlock-run',size:elf.length,sha256:sha(elf)},patchSha256:sha(patch),builderDpkgSha256:sha(dpkg)};
 put(platform,'package.json',pkg);put(platform,'artifact-manifest.json',manifest);for(const s of [manifest.bridge,manifest.launcher])put(platform,s.path,elf);put(platform,'provenance/codex-bridge-development.patch',patch);put(platform,'provenance/builder-dpkg.txt',dpkg);put(audit,'codex-bridge-development.patch',patch);
 for(const [file,value]of Object.entries({'package.json':hp,'expected-provenance.json':{package:pkg,manifest},'index.mjs':'inert index','bridge-owner.mjs':'inert owner'})){put(host,file,value);put(audit,'packages/host/'+file,value);}
 return{root,platform,host,audit,manifest,pkg,hp,put};}
test('artifact/pin checks accept consistent inert bytes without executing them',()=>{const f=fixture();assert.equal(verifyPackagePins(f.platform,f.host,f.audit).packageVersion,'0.1.0-rc.2');});
test('changed native bytes or audited host source cannot pass pins',()=>{for(const field of ['binary','host']){const f=fixture();if(field==='binary')f.put(f.platform,f.manifest.bridge.path,'changed');else f.put(f.host,'index.mjs','changed');assert.throws(()=>verifyPackagePins(f.platform,f.host,f.audit));}});
test('manifest path traversal is refused even when host JSON repeats it',()=>{const f=fixture();f.manifest.bridge.path='../arbitrary-exec';f.put(f.platform,'artifact-manifest.json',f.manifest);f.put(f.host,'expected-provenance.json',{package:f.pkg,manifest:f.manifest});f.put(f.audit,'packages/host/expected-provenance.json',{package:f.pkg,manifest:f.manifest});assert.throws(()=>verifyPackagePins(f.platform,f.host,f.audit));});
test('cross-version platform/host pins fail closed',()=>{const f=fixture();f.hp.optionalDependencies[f.pkg.name]='0.1.0-rc.1';f.put(f.host,'package.json',f.hp);assert.throws(()=>verifyPackagePins(f.platform,f.host,f.audit));});
test('package readers reject root/file aliases, traversal, directories and oversized bytes',()=>{const f=fixture();symlinkSync(f.platform,join(f.root,'alias'));assert.throws(()=>canonicalRoot(join(f.root,'alias')));symlinkSync(join(f.platform,'package.json'),join(f.platform,'link'));for(const name of ['link','../host/package.json','bin','/etc/passwd'])assert.throws(()=>readPackageFile(f.platform,name));assert.throws(()=>readPackageFile(f.platform,'package.json',1));});
test('wire generation preserves raw i64 values, not rounded JS numbers',()=>{const requests=smokeRequests();assert(requests[2].wire.includes('9223372036854775807'));assert(requests[3].wire.includes('9223372036854775808'));});
function responses(manifest){return[{id:'h',session_id:'ci-native-smoke',ok:true,result:{protocol:2,irVersion:1,upstreamCommit:'9f97cb79eb15b38d24c552c56fe24e211ff9cf3a',bridgePatchSha256:manifest.patchSha256,os:'linux',arch:'x86_64',hardening:{noNewPrivileges:true,network:'seccomp-deny',filesystem:'seccomp-deny-open-plus-launcher',rlimits:true}}},...['-9223372036854775808','9223372036854775807'].map((value,i)=>({id:'i'+i,session_id:'ci-native-smoke',ok:true,result:{ir:{startedAtMs:value},canonicalWire:'{"started_at_ms":'+value+'}'}})),{id:'i2',session_id:'ci-native-smoke',ok:false,error:{kind:'serde'}}];}
test('protocol validator checks handshake, session, precision, overflow and complete frames',()=>{const f=fixture(),encode=r=>r.map(x=>JSON.stringify(x)).join('\n')+'\n';assert.equal(validateSmokeOutput(encode(responses(f.manifest)),f.manifest).frames,4);
 for(const change of [r=>r[0].result.bridgePatchSha256='wrong',r=>r[0].result.hardening.filesystem='none',r=>r[0].result.hardening.rlimits=false,r=>r[1].session_id='wrong',r=>r[2].result.ir.startedAtMs=9223372036854775807,r=>r[3].ok=true,r=>r.push(r[0])]){const r=responses(f.manifest);change(r);assert.throws(()=>validateSmokeOutput(encode(r),f.manifest));}assert.throws(()=>validateSmokeOutput(encode(responses(f.manifest)).trimEnd(),f.manifest));});
